In [ ]:
import numpy as np
import pandas as pd
"""Q1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type."""
a = [0,1,2,3,4,5]
arr = np.array(a)
type(arr)

numpy.ndarray

In [17]:
""" Q2. Given a NumPy array 'arr', check if its data type is float64. arr = np.array([1.5, 2.6, 3.7])."""
arr = np.array([1.5, 2.6, 3.7])
type(arr[0])
type(arr[1])
type(arr[2])

numpy.float64

In [5]:
""" Q3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
SOL."""
arr = np.array([1+8j,8-5j,3+7j])
type(arr[0])

numpy.complex128

In [16]:
""" Q4. Convert an existing NumPy array 'arr' of integers to float32 data type."""
a = [0,1,2,3,4,5]
arr = np.array(a)
arr1 = arr.astype("float32")
print(arr1)

[0. 1. 2. 3. 4. 5.]


In [15]:
""" Q5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision."""
arr = np.array([1.5, 2.6, 3.7])
print(type(arr[0]))
arr1 = arr.astype("float32")
type(arr1[0])

<class 'numpy.float64'>


numpy.float32

In [25]:
""" Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type."""

def array_attribute(x):
    a = x.shape
    b = x.size
    c = type(x[0])
    return a,b,c

arr = np.array([[1,2.3,4.8],[1,3.2,15]])

array_attribute(arr)

((2, 3), 6, numpy.ndarray)

In [26]:
""" Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality."""

def array_dimension(x):
    return x.ndim

arr = np.array([[1,2.3,4.8],[1,3.2,15]])

array_dimension(arr)

2

In [28]:
""" Q8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes."""
def item_size_info(x):
    a = x.size
    b = x.nbytes
    return a,b

arr = np.array([[1,2.3,4.8],[1,3.2,15]])

item_size_info(arr)

(6, 48)

In [29]:
""" Q9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array."""

def array_strides(x):
    return x.strides
    
arr = np.array([[1,2.3,4.8],[1,3.2,15]])

array_strides(arr)

(24, 8)

In [30]:
""" 
Q10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array."""

arr = np.array([[1,2.3,4.8],[1,3.2,15]])
def shape_strides_relationship(x):
    a = x.shape
    b = x.strides
    return a,b

shape_strides_relationship(arr)

((2, 3), (24, 8))

In [36]:
""" 
Q11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
"""
def create_zeros_array(n):
    a = np.zeros([n])
    return a
create_zeros_array(5)

array([0., 0., 0., 0., 0.])

In [38]:
""" Q12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array 
         filled with ones of size `rows x cols`."""
def create_ones_matrix(rows,cols):
    a = np.ones([rows,cols])
    b = a.size
    return a,b
create_ones_matrix(2,3)

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 6)

In [45]:
""" Q13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy 
         array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`."""

def generate_range_array(start,stop,step):
    a = np.arange(start,stop,step)
    return a

generate_range_array(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [49]:
""" Q14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and 
         generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive)."""

def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)

generate_linear_space(0.5,30.5,10)

array([ 0.5       ,  3.83333333,  7.16666667, 10.5       , 13.83333333,
       17.16666667, 20.5       , 23.83333333, 27.16666667, 30.5       ])

In [51]:
""" Q15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of 
         size `n x n` using `numpy.eye`."""

def create_identity_matrix(n):
    return np.eye(n,n)
create_identity_matrix(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
""" Q16. Write a function that takes a Python list and converts it into a NumPy array."""
def convert_list(a):
    return np.array(a)

convert_list([1,5.5,7,36,2.5])

array([ 1. ,  5.5,  7. , 36. ,  2.5])

In [59]:
""" Q17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data."""

arr = np.array([[1,2.3,4.8],[1,3.2,15]])
arr1 = arr.view()
arr1

array([[ 1. ,  2.3,  4.8],
       [ 1. ,  3.2, 15. ]])

In [82]:
"""Q18. Write a function that takes two NumPy arrays and concatenates them along a specified axis."""

def concatenate_arrays(arr1, arr2, axis= 0):
    return np.concatenate((arr1,arr2), axis = axis)

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])
concatenate_arrays(arr1,arr2,axis= 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
"""Q19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`."""

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2),axis= 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [91]:
"""Q20. Write a function that vertically stacks multiple NumPy arrays given as a list."""

def vertical_stack_arrays(arrays_list):
    num_columns = arrays_list[0].shape[1]
    return np.vstack(arrays_list)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
array3 = np.array([[7, 8], [9, 10]])

vertical_stack_arrays([array1, array2, array3])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
"""
Q21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
"""

def py_array(start,stop,step_size):
    return np.arange(start,stop+1,step_size)


a=py_array(1,20,4)
a

array([ 1,  5,  9, 13, 17])

In [9]:
"""Q22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive)."""

def py_equal(start,stop,numbers):
    return np.linspace(start,stop,numbers)

py_equal(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
"""
Q23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive)."""

def log_values(start,stop):
    
    return np.logspace(np.log10(start), np.log10(stop), 5)

log_values(1,1000)
        

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [2]:
"""
Q24.  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers
between 1 and 100."""

a = np.random.randint(1,100,(5,3))
b = pd.DataFrame(a)
b

0   1   2
0   2  60  50
1  24  28  73
2  66  97  40
3  27  23  21
4  21  19  54

In [132]:
def replaces(df,column_name):
    for i in df["column_name"]:
        np.where(i<0,[0,i])
    return df["column_name"]

In [4]:
"""
Q25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros.
Use NumPy operations within the Pandas DataFrame.
"""

aa ={"values":[1,8,96,75,10,-96,25,-6,-78,20,15]}

df =  pd.DataFrame(aa)

def replaces(df,column_name):
    df["column_name"] = df[column_name].map(lambda x: 0 if x<0 else x)
    print( df["column_name"])

#Ex:
column_name = "values"
df 
replaces(df,column_name)

0      1
1      8
2     96
3     75
4     10
5      0
6     25
7      0
8      0
9     20
10    15
Name: column_name, dtype: int64


In [16]:
"""Q26. Access the 3rd element from the given NumPy array."""

arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [19]:
"""Q27. Retrieve the element at index (1, 2) from the 2D NumPy array.
 arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
"""

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[(1,2)]

6

In [21]:
""" Q28. Using boolean indexing, extract elements greater than 5 from the given NumPy array. arr = np.array([3, 8, 2, 10, 5, 7])"""

arr = np.array([3,8,2,10,5,7])
arr[arr>5]

array([ 8, 10,  7])

In [26]:
""" Q 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])"""

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:5]

array([3, 4, 5])

In [42]:
""" Q 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])"""


arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

arr_want = arr_2d[0:2,1:3]
arr_want

array([[2, 3],
       [5, 6]])

In [64]:
""" Q31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in 
another array."""

df = np.array([[85,47,-96,25,-14],[97,-85,26,-91,36],[84,62,-35,-24,87],[-96,78,-25,93,58]])
df1 = np.array([[1,2,4,3],[0,1,4,3],[3,2,1,4]])


def extract(df,df1):
    a = df1.ravel() + np.repeat(range(0,df.shape[1]*df1.shape[0],df.shape[1]),df1.shape[1])
    result = df.ravel()[a].reshape(df1.shape)
    return result
extract(df,df1)

array([[ 47, -96, -14,  25],
       [ 97, -85,  36, -91],
       [-24, -35,  62,  87]])

In [66]:
"""Q32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing."""

def filters(x,number):
    return x[x>number]

arr = np.array([8,4,3,2,1,6,7,9,42,15,38,64])

filters(arr,10)

array([42, 15, 38, 64])

In [74]:
"""Q33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays
for each dimension."""
arr1 = np.random.randint(1,100,(3,3,3))
print(arr1)
arr_row = np.array([0,1,2])
arr_col = np.array([0,2,1])
arr_dim = np.array([1,2,0])

def extract_element(arr1,arr2,arr3,arr4):
    extracted_element = arr1[np.random.choice(arr_dim),np.random.choice(arr_row),np.random.choice(arr_col)]
    return extracted_element

extract_element(arr1,arr_row,arr_col,arr_dim)

[[[51 50 51]
  [57 87 41]
  [15 94 87]]

 [[ 2  1  9]
  [11 63 63]
  [44 25 10]]

 [[50 39 13]
  [40  6 38]
  [69 74 24]]]


11

In [72]:
"""Q34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing."""

arr = np.array([8,4,3,2,1,6,7,9,42,15,38,64])

arr[(arr>6)& (arr<40)]

array([ 8,  7,  9, 15, 38])

In [95]:
""" Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays."""

df = np.array([[1,2,4,3],[0,1,4,3],[3,2,1,4],[48,63,87,15]])
df1 = np.array([0,2,1,3])
df2 = np.array([0,3,1,2])

def ext_2d(df,df1,df2):
    return df[df1,df2]


ext_2d(df,df1,df2)

array([ 1,  4,  1, 87])

In [102]:
"""Q36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting."""

arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr+ 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [114]:
"""Q37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding
element in arr1 using NumPy broadcasting."""

arr1 = np.array([[1,2,3]])
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a= arr1.T
arr2*a

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36]])

In [117]:
""" Q38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
NumPy broadcasting."""

arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[1,2,3],[5,6,7],[9,10,11],[4,8,12]])
a= arr1.T
arr2+a

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [ 8, 12, 16]])

In [123]:
""" Q39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting."""

arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[4,5,6]])
arr1+arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [67]:
""" Q40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. 
Handle the shape incompatibility."""

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8],[9,10]])
a = arr1.reshape(3,2,1)
a*arr2

array([[[ 7,  8],
        [18, 20]],

       [[21, 24],
        [36, 40]],

       [[35, 40],
        [54, 60]]])

In [11]:
""" Q41. Calculate column-wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])"""

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [14]:
""" Q42. Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])"""

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=1)

array([3, 6])

In [16]:
""" Q43. For the given array, find indices of maximum value in each column. arr = np.array([[1, 2, 3], [4, 5, 6]])"""

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=0)

array([4, 5, 6])

In [18]:
""" Q44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])"""

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.sum(axis=1)

array([ 6, 15])

In [25]:
""" Q45. In the given array, check if all elements in each column are even. arr = np.array([[2, 4, 6], [3, 5, 7]])"""

arr = np.array([[2, 4, 6], [3, 5, 7]])
np.all(arr%2==0)

False

In [28]:
"""Q46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
reshaped matrix. original_array = np.array([1, 2, 3, 4, 5, 6])"""

original_array = np.array([1, 2, 3, 4, 5, 6])
new_array = original_array.reshape(3,2)
new_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
"""Q47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])"""

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatterned_array(a):
    b = a.flatten()
    return b

flatterned_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [61]:
""" Q48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])  array2 = np.array([[5, 6], [7, 8]])"""

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concated(a,b,axis):
    c = np.concatenate((a,b),axis=axis)
    return c

concated(array1,array2,0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
""" Q49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])"""


original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_array = original_array.reshape(3,3,1)
new_array

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [2]:
""" Q50.  Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5]) indices_to_insert = [2, 4]
values_to_insert = [10, 11]  indices_to_delete = [1, 3]"""

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]  
indices_to_delete = [1, 3]

def edit_array(orgi,indice_insert,insert_array,indice_delete):
    orgi = np.insert(orgi,indice_insert,insert_array)
    orgi = np.delete(orgi,indice_delete)
    return orgi

edit_array(original_array,indices_to_insert,values_to_insert,indices_to_delete)

array([ 1, 10,  4, 11,  5])

In [9]:
""" Q51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`."""

arr1 = np.random.random((3,3))
arr2 = np.random.randint(1,10,(3,3))

print(arr1,arr2)

arr1+arr2

[[0.36817345 0.29864644 0.10620263]
 [0.61817778 0.90045762 0.60330997]
 [0.9010497  0.85880838 0.85923436]] [[5 6 5]
 [7 7 2]
 [3 6 5]]


array([[5.36817345, 6.29864644, 5.10620263],
       [7.61817778, 7.90045762, 2.60330997],
       [3.9010497 , 6.85880838, 5.85923436]])

In [14]:
""" Q52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
from 1 to 10. Subtract `arr2` from `arr1` element-wise."""

arr1 = np.array(range(10,0,-1))
arr2 = np.array(range(1,11))

print(arr1,arr2)

arr2-arr1

[10  9  8  7  6  5  4  3  2  1] [ 1  2  3  4  5  6  7  8  9 10]


array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

In [16]:
""" Q53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
Perform element-wise multiplication between `arr1` and `arr2`."""

arr1 = np.random.random((3,3))
arr2 = np.random.randint(1,5,(3,3))

print(arr1,arr2)

arr1*arr2

[[0.48562474 0.35653962 0.93082773]
 [0.83526397 0.70311435 0.12557183]
 [0.57950534 0.78141581 0.75181447]] [[2 1 3]
 [1 2 1]
 [3 1 1]]


array([[0.97124949, 0.35653962, 2.79248319],
       [0.83526397, 1.4062287 , 0.12557183],
       [1.73851601, 0.78141581, 0.75181447]])

In [22]:
""" Q54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
to 5. Perform element-wise division of `arr1` by `arr2`."""

a=[]
for i in range(2,11):
    if i%2==0:
        a.append(i)
a
arr1 = np.random.choice(a,(3,3))
arr2= np.random.randint(1,5,(3,3))

print(a,arr1,arr2)
arr1/arr2

[2, 4, 6, 8, 10] [[ 8  8  2]
 [ 8  4  6]
 [ 4 10  4]] [[1 3 4]
 [4 2 4]
 [1 1 3]]


array([[ 8.        ,  2.66666667,  0.5       ],
       [ 2.        ,  2.        ,  1.5       ],
       [ 4.        , 10.        ,  1.33333333]])

In [29]:
""" Q55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise."""

arr1= np.array(range(1,6))
arr2= np.array(range(5,0,-1))
print(arr1,arr2)

a=arr1**arr2
a

[1 2 3 4 5] [5 4 3 2 1]


array([ 1, 16, 27, 16,  5])

In [46]:
""" Q56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])"""

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def word_in_array(arr,word):
    return np.sum(i.count(word) for i in arr)

word_in_array(arr,"world")

1

In [56]:
""" Q57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])"""

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def ext_upper(a):
    b=[]
    for i in a:
        for j in i:
            if j==j.upper():
                b.append(j)
    return b
            
ext_upper(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

In [64]:
""" Q58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])"""

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


def replace_string(arr,word,new_string):
    return np.char.replace(arr,word,new_string)


replace_string(arr,"apple","mango")

array(['mango', 'banana', 'grape', 'pinemango'], dtype='<U9')

In [69]:
""" Q59. Write a function that concatenates strings in a NumPy array element-wise.
 arr1 = np.array(['Hello', 'World']) arr2 = np.array(['Open', 'AI'])"""

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concate_array(arr1,arr2):
    return np.char.add(arr1,arr2)

concate_array(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [71]:
""" Q60. Write a function that finds the length of the longest string in a NumPy array.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])"""

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def highest_len(x):
    b=[]
    for i in x:
        b.append(len(i))
    return max(b)

highest_len(arr)

9

In [99]:
""" Q61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
standard deviation of the dataset using NumPy's functions."""

a= np.random.randint(1,1000,(100))
a

# mean
np.mean(a)
# median
np.median(a)
# std
b=np.std(a)
b
# variance
np.sqrt(b)

17.376092680949277

In [105]:
""" Q62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
dataset."""

p = np.random.randint(1,100,50)


np.percentile(p,[25,75])

array([24., 76.])

In [109]:
"""Q63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
arrays using NumPy's `corrcoef` function."""

a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([10,9,8,7,6,5,4,3,2,1])
np.corrcoef(a,b)

array([[ 1., -1.],
       [-1.,  1.]])

In [113]:
"""Q64. Create two matrices and perform matrix multiplication using NumPy's `dot` function."""

mat1 = np.mat([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.mat([[8,5,2],[9,5,1],[7,5,3]])

np.dot(mat1,mat2)

matrix([[ 47,  30,  13],
        [119,  75,  31],
        [191, 120,  49]])

In [117]:
""" Q65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
percentiles along with the first and third quartiles."""

d = np.random.randint(10,1000,50)

np.percentile(d,[10,25,50,75,90])

array([164.3 , 254.25, 474.  , 788.  , 903.2 ])

In [121]:
""" Q66. Create a NumPy array of integers and find the index of a specific element."""

o = np.array([85,75,96,14,76])


In [128]:
""" Q67. Generate a random NumPy array and sort it in ascending order."""

o = np.array([85,75,96,14,76])
sorted(o)

[14, 75, 76, 85, 96]

In [130]:
""" Q68. Filter elements >20  in the given NumPy array. arr = np.array([12, 25, 6, 42, 8, 30])"""
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

In [132]:
"""Q69. Filter elements which are divisible by 3 from a given NumPy array. arr = np.array([1, 5, 8, 12, 15])"""

arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

In [139]:
""" Q 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array. arr = np.array([10, 20, 30, 40, 50])"""

arr = np.array([10, 20, 30, 40, 50])
arr[(arr>=20)&(arr<=40)]

array([20, 30, 40])

In [140]:
""" Q71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder. arr = np.array([1, 2, 3])"""

arr = np.array([1, 2, 3])
arr.dtype.byteorder

'='

In [142]:
"""Q72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
 arr = np.array([1, 2, 3], dtype=np.int32)"""

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

In [144]:
""" Q73. For the given NumPy array, swap its byte order without modifying the original array using 
`newbyteorder()`. arr = np.array([1, 2, 3], dtype=np.int32)"""

arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder("<")

array([1, 2, 3], dtype=int32)

In [147]:
"""Q 74. For the given NumPy array and swap its byte order conditionally based on system endianness using 
`newbyteorder()`. arr = np.array([1, 2, 3], dtype=np.int32)"""

arr = np.array([1, 2, 3], dtype=np.int32)
arr1 = arr.dtype.byteorder
swap_arr = arr.newbyteorder(arr1)
swap_arr

array([1, 2, 3], dtype=int32)

In [149]:
"""  75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
attribute `byteorder`. arr = np.array([1, 2, 3], dtype=np.int32)"""

arr = np.array([1, 2, 3], dtype=np.int32)
system_endianness = arr.dtype.byteorder

if system_endianness == '=':
    print("Array byte order matches system (no swapping needed)")
else:
    print(f"Array byte order ({system_endianness}) differs from system")

Array byte order matches system (no swapping needed)


In [152]:
""" Q76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`."""

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

copy_arr = arr1

copy_arr[2]= 85

copy_arr[2]==arr1[2]

True

In [155]:
""" Q77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`."""

arr2 = np.random.randint(1,10,(3,3))
view_slice=arr2[2]
view_slice[2] = 95
view_slice[2]==arr2[2,2]

True

In [8]:
"""Q78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`."""

array = np.arange(1, 13)
array_a = array.reshape(4,3)
array_a

view_b = array_a[1]

view_b+5 == array_a[1]

array([False, False, False])

In [15]:
""" Q79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
reflects changes in the original `orig_array`."""

array = np.arange(1,9)
orig_array= array.reshape(2,4)
reshaped_view= orig_array.reshape(4,2)
reshaped_view[2,0]=58
orig_array.reshape(4,2) == reshaped_view

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [26]:
""" Q 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`."""

data = np.random.randint(1,15,(3,4))
data_copy = data[data > 5].copy()
data_copy[(0)] = 99
np.array_equal(data, data_copy)

False

In [28]:
"""Q81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
operations between them."""

A = np.random.randint(1, 10, size=(2, 3))
B = np.random.randint(1, 10, size=(2, 3))
addition_result = A + B
subtraction_result = A - B
print(subtraction_result,addition_result)

[[ 2 -3  5]
 [ 4 -2 -2]] [[14  5 11]
 [14 10 10]]


In [30]:
""" Q 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication."""
D = np.array([[1,2,3,4],[5,6,7,8]])
C=np.array([[10,11],[12,13],[14,15]])

C@D

array([[ 65,  86, 107, 128],
       [ 77, 102, 127, 152],
       [ 89, 118, 147, 176]])

In [32]:
"""Q83. Create a matrix `E` and find its transpose"""

E = np.array([[1,2,3,4],[5,6,7,8]])
E.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [36]:
"""Q84. Generate a square matrix `F` and compute its determinant."""
F = np.array([[2,5],[8,9]])

np.linalg.det(F)

-21.999999999999996

In [37]:
"""Q 85. Create a square matrix `G` and find its inverse."""
G = np.array([[2,5],[8,9]])
np.linalg.inv(G)

array([[-0.40909091,  0.22727273],
       [ 0.36363636, -0.09090909]])